[project]
name = "music-genre-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.0",
    "kagglehub>=0.3.13",
]
